project_id = "phsvqizffyyqjygqdgdl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = false

[db]
enabled = true
port = 54322
major_version = 15

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54325

[functions.generate-with-ai]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.claude-copywriter]
verify_jwt = false

[functions.context-processor]
verify_jwt = true